backend:
  name: github
  repo: susanqxh/qxh‑techco‑website
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: pages
    label: Pages
    files:
      - name: index
        label: Home Page
        file: "index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
